### ISSUE TITLE
error in flash missing data imputation with ebnm_pn

### ISSUE THREAD

**Issue by NKweiwang** [stephenslab/ebnm#1]
I tried flash for missing data imputation with ebnm_fn = ebnm_pn in 10 fold OCV. 
There is an error message 
```Error in optim(startpar, function(par, x, s) { : 
  non-finite value supplied by optim
Error in mle_normal_logscale_grad(x, s) : 
  optim failed to converge; debug information saved to temp_debug.RDS
```
which stops the `flash` code, and there is a `temp_debug.RDS` file the the currently working folder.

please take a look at the .rds file. (.rds is not supported, so I use zip file)

Thanks a lot. 

[temp_debug.RDS.zip](https://github.com/stephenslab/ebnm/files/1639948/temp_debug.RDS.zip)

**Comment by stephens999** [comment]
this was due to very small s and x values making things numerically unstable. Fixed in 
2c6fc9032d2f013c48a60e982199c4a70da868e4
