### ISSUE TITLE
ebnm_scale_mix_normal (ebnm_ash)

### ISSUE THREAD

**Issue by stephens999** [stephenslab/ebnm#15]

**Comment by stephens999** [comment]
maybe we should consider implementing a version of ash that just does scale mixture of normals in the ebnm suite, with a focus on speed.

the point is that ash is designed to be general, and this comes with overhead in terms of code speed
and complexity. The special case of a scale mixture of normals with normal likelihood is maybe important and simple enough to deserve a purpose built function in ebnm that is designed for speed?

**Comment by pcarbo** [comment]
I'm happy to help with this.

**Comment by willwerscheid** [comment]
Where are you thinking we can get performance gains? It would still be solved using `mixsqp`, right? Are you thinking about more efficient computation of the likelihood matrix? of the summary results? Both are possible I think. Anything else?

**Comment by stephens999** [comment]
Yes, both those and nothing else. I did not have anything sophisticated in mind. And so I'm not sure h how much does gain we'd get. But it would not be hard to try
