### ISSUE TITLE
implement plot.ebnm, summary.ebnm, print.summary.ebnm

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/ebnm#24]
For `plot`, maybe do `x` vs. `posterior$mean` (would need to return `x` and `s` in a data frame called `data`). @pcarbo 's suggestions for `summary`:

+ sample size
+ prior type
+ scale (fixed or estimated)
+ quantiles of input data, posterior means, and lfsr.
+ g (fixed or estimated)

**Comment by willwerscheid** [comment]
For `plot`, can also use `plot_diagnostic` from `ashr`.

**Comment by pcarbo** [comment]
@willwerscheid Take a look at the [varbvs package](https://github.com/pcarbo/varbvs) to get started on implementing these functions.

**Comment by willwerscheid** [comment]
The plotting code for the wOBA example from my thesis should work
