### ISSUE TITLE
ebnm_npmle can call ebnm_normal_scale_mix

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/ebnm#52]
right now it calls ebnm_ash but why not use the faster function

**Comment by stephens999** [comment]
using a mixture of normals for npmle is probably slower than just using a discrete grid of point masses? 
probably worth coding up the discrete grid directly? (in ash i only used the mixture of normals/uniforms
to avoid doing the special case....)

**Comment by willwerscheid** [comment]
good point! i don't think the gains would be terribly significant but it shouldn't be too hard to implement (really 2-3 lines I think). and i think i have to make a couple of changes anyway because `ebnm_normal_mix_workhorse` previously assumed a scalar "mode" parameter whereas the way this is implemented is like a vector of modes.
