### ISSUE TITLE
Add ebnm_point_mass, improper uniform prior

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/ebnm#83]
Would be a useful way to "fix" elements using group priors. Another useful function would just return x and s as is (might be useful for "mean" factors in flash). I am not sure what to call this one. ebnm_improper_uniform is unwieldy. ebnm_identity? ebnm_no_prior? ebnm_flat?

**Comment by stephens999** [comment]
ebnm_flat seems ok. Or ebnm_improper?
