### ISSUE TITLE
wOBA is a tibble

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/ebnm#99]
I noticed that the `wOBA` data set is a "tibble":

```
> data(wOBA)
> class(wOBA)
[1] "baseballr_data" "tbl_df"         "tbl"            "data.table"
[5] "data.frame"
```

This introduces a dependency on the `tibble` package, which doesn't seem necessary. Maybe you can make it a (more standard) data frame? 

Also, can I suggest making the Team column a factor, and replacing the "---"s with NAs, which is what is conventionally done in R?

**Comment by willwerscheid** [comment]
yes you are right. in fact it requires the `baseballr` package. i will run `as.data.frame()` before saving.

**Comment by willwerscheid** [comment]
fixed
